name: Mi primer workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje
        run: echo "Hola, GitHub Actions está vivo! 🚀"
        name: crear archivo con la version 